import type { FormMetadata } from "../types/metadata";
import React from "react";
import { FiCalendar, FiMapPin, FiUsers, FiDollarSign } from "react-icons/fi";

export const eventFormMetadata: FormMetadata = {
  entityName: "event",
  title: "Evento",
  description: "Preencha os dados do evento esportivo",
  endpoint: "/api/events",
  successRedirect: "/eventos",
  submitLabel: "Criar Evento",
  cancelLabel: "Cancelar",

  sections: [
    {
      id: "basic-info",
      title: "Informações Básicas",
      icon: React.createElement(FiCalendar),
      columns: 2,
      fields: [
        {
          name: "name",
          label: "Nome do Evento",
          type: "text",
          placeholder: "Ex: Corrida da Montanha 2024",
          required: true,
          validation: {
            minLength: 3,
            maxLength: 100,
            message: "O nome deve ter entre 3 e 100 caracteres",
          },
        },
        {
          name: "eventType",
          label: "Tipo de Evento",
          type: "select",
          required: true,
          options: [
            { value: "RUNNING", label: "Corrida" },
            { value: "CYCLING", label: "Ciclismo" },
            { value: "TRIATHLON", label: "Triatlo" },
            { value: "TRAIL", label: "Trail" },
            { value: "OBSTACLE", label: "Corrida de Obstáculos" },
            { value: "OTHER", label: "Outro" },
          ],
        },
        {
          name: "date",
          label: "Data do Evento",
          type: "date",
          required: true,
        },
        {
          name: "registrationDeadline",
          label: "Prazo de Inscrição",
          type: "date",
          required: true,
        },
        {
          name: "description",
          label: "Descrição",
          type: "textarea",
          placeholder: "Descreva o evento, incluindo informações importantes para os participantes",
          required: true,
          validation: {
            minLength: 20,
            maxLength: 2000,
          },
        },
        {
          name: "categories",
          label: "Categorias do Evento",
          type: "array",
          required: true,
          arrayConfig: {
            itemType: "object",
            addLabel: "Adicionar Categoria",
            itemLabel: "Categoria {index}",
            minItems: 1,
            maxItems: 10,
            fields: [
              {
                name: "name",
                label: "Nome da Categoria",
                type: "text",
                placeholder: "Ex: 5km Masculino",
                required: true,
              },
              {
                name: "distance",
                label: "Distância (km)",
                type: "number",
                placeholder: "Ex: 5",
                required: true,
                validation: {
                  min: 0.1,
                  max: 500,
                },
              },
              {
                name: "price",
                label: "Preço (R$)",
                type: "number",
                placeholder: "Ex: 50.00",
                required: true,
                validation: {
                  min: 0,
                },
              },
              {
                name: "maxParticipants",
                label: "Vagas",
                type: "number",
                placeholder: "Ex: 100",
                validation: {
                  min: 1,
                },
              },
            ],
          },
        },
      ],
    },
    {
      id: "location",
      title: "Localização",
      icon: React.createElement(FiMapPin),
      columns: 2,
      fields: [
        {
          name: "location",
          label: "Local",
          type: "text",
          placeholder: "Ex: Parque da Cidade",
          required: true,
        },
        {
          name: "address",
          label: "Endereço",
          type: "text",
          placeholder: "Rua, número",
        },
        {
          name: "city",
          label: "Cidade",
          type: "text",
          required: true,
        },
        {
          name: "state",
          label: "Estado",
          type: "select",
          required: true,
          options: [
            { value: "AC", label: "Acre" },
            { value: "AL", label: "Alagoas" },
            { value: "AP", label: "Amapá" },
            { value: "AM", label: "Amazonas" },
            { value: "BA", label: "Bahia" },
            { value: "CE", label: "Ceará" },
            { value: "DF", label: "Distrito Federal" },
            { value: "ES", label: "Espírito Santo" },
            { value: "GO", label: "Goiás" },
            { value: "MA", label: "Maranhão" },
            { value: "MT", label: "Mato Grosso" },
            { value: "MS", label: "Mato Grosso do Sul" },
            { value: "MG", label: "Minas Gerais" },
            { value: "PA", label: "Pará" },
            { value: "PB", label: "Paraíba" },
            { value: "PR", label: "Paraná" },
            { value: "PE", label: "Pernambuco" },
            { value: "PI", label: "Piauí" },
            { value: "RJ", label: "Rio de Janeiro" },
            { value: "RN", label: "Rio Grande do Norte" },
            { value: "RS", label: "Rio Grande do Sul" },
            { value: "RO", label: "Rondônia" },
            { value: "RR", label: "Roraima" },
            { value: "SC", label: "Santa Catarina" },
            { value: "SP", label: "São Paulo" },
            { value: "SE", label: "Sergipe" },
            { value: "TO", label: "Tocantins" },
          ],
        },
      ],
    },
    {
      id: "registration",
      title: "Inscrições",
      icon: React.createElement(FiUsers),
      columns: 2,
      fields: [
        {
          name: "maxParticipants",
          label: "Máximo de Participantes",
          type: "number",
          placeholder: "Ex: 500",
          validation: {
            min: 1,
            max: 100000,
          },
        },
        {
          name: "registrationFee",
          label: "Taxa de Inscrição (R$)",
          type: "number",
          placeholder: "Ex: 50.00",
          required: true,
          validation: {
            min: 0,
          },
        },
        {
          name: "allowTeamRegistration",
          label: "Permitir Inscrição em Equipe",
          type: "boolean",
          defaultValue: false,
        },
        {
          name: "teamSize",
          label: "Tamanho da Equipe",
          type: "number",
          placeholder: "Ex: 4",
          showIf: "data.allowTeamRegistration === true",
          validation: {
            min: 2,
            max: 10,
          },
        },
      ],
    },
    {
      id: "payment",
      title: "Pagamento",
      icon: React.createElement(FiDollarSign),
      columns: 2,
      fields: [
        {
          name: "acceptCard",
          label: "Aceitar Cartão de Crédito",
          type: "boolean",
          defaultValue: true,
        },
        {
          name: "acceptPix",
          label: "Aceitar PIX",
          type: "boolean",
          defaultValue: true,
        },
        {
          name: "acceptBankSlip",
          label: "Aceitar Boleto Bancário",
          type: "boolean",
          defaultValue: false,
        },
        {
          name: "installments",
          label: "Número de Parcelas (Cartão)",
          type: "number",
          placeholder: "Ex: 3",
          showIf: "data.acceptCard === true",
          defaultValue: 1,
          validation: {
            min: 1,
            max: 12,
          },
        },
      ],
    },
    {
      id: "additional",
      title: "Informações Adicionais",
      icon: React.createElement(FiDollarSign),
      columns: 1,
      fields: [
        {
          name: "tags",
          label: "Tags do Evento",
          type: "array",
          arrayConfig: {
            itemType: "text",
            addLabel: "+ Adicionar Tag",
            itemLabel: "Tag {index}",
            placeholder: "Ex: corrida, trail, montanha",
            maxItems: 10,
          },
        },
        {
          name: "prizes",
          label: "Premiações",
          type: "array",
          arrayConfig: {
            itemType: "object",
            addLabel: "Adicionar Premiação",
            itemLabel: "Premiação {index}",
            maxItems: 10,
            fields: [
              {
                name: "position",
                label: "Posição",
                type: "select",
                required: true,
                options: [
                  { value: "1", label: "1º Lugar" },
                  { value: "2", label: "2º Lugar" },
                  { value: "3", label: "3º Lugar" },
                  { value: "4", label: "4º Lugar" },
                  { value: "5", label: "5º Lugar" },
                ],
              },
              {
                name: "category",
                label: "Categoria",
                type: "text",
                placeholder: "Ex: Geral Masculino",
                required: true,
              },
              {
                name: "prize",
                label: "Prêmio",
                type: "text",
                placeholder: "Ex: R$ 500,00",
                required: true,
              },
            ],
          },
        },
      ],
    },
  ],
};
